apiVersion: v1
kind: Namespace
metadata:
  name: goodfood

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: goodfood
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: project
          emptyDir: {}
      initContainers:
        - name: git-cloner
          image: alpine/git
          args: ["clone", "--single-branch", "https://github.com/cmm-goodfood/api", "/project"]
          volumeMounts:
            - mountPath: /project
              name: project
        - name: gradle
          image: gradle:6.7-jdk8
          args: ["gradle", "jar"]
          workingDir: /project
          volumeMounts:
            - mountPath: /project
              name: project
      containers:
        - name: api
          image: openjdk:15-jdk
          command: ["java", "-jar", "build/libs/api.jar"]
          workingDir: /project
          volumeMounts:
            - name: project
              mountPath: /project

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: goodfood
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: api

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: goodfood
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
spec:
  tls:
    - hosts: ["api.follow-gt.fr"]
      secretName: api-tls
  rules:
    - host: api.follow-gt.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: api
              servicePort: 80